# hyprlock : uniquement une capture de l'écran floutée, sans widgets.
general {
    hide_cursor = true
    ignore_empty_input = true
}

background {
    monitor =
    path = screenshot
    blur_passes = 3
    blur_size = 8
    noise = 0.01
    brightness = 0.8
}
