# Laisser niri gérer entièrement les décorations :
# pas de barre de titre dessinée par foot, juste le border/focus-ring de niri.
[csd]
preferred=none
[main]
font=Geist Mono Font:size=10
include=/usr/share/foot/themes/srcery
